"""empty message

Revision ID: e3a72926f808
Revises: c3803ac9b7dd
Create Date: 2016-08-10 19:12:49.647496

"""

# revision identifiers, used by Alembic.
revision = 'e3a72926f808'
down_revision = 'c3803ac9b7dd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('postmaster_admins', sa.Column('otp_active', sa.Boolean(), nullable=True))
    op.add_column('postmaster_admins', sa.Column('otp_secret', sa.String(length=16), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('postmaster_admins', 'otp_secret')
    op.drop_column('postmaster_admins', 'otp_active')
    ### end Alembic commands ###
